# Generated by Django 4.1.7 on 2024-08-25 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rakuraku_apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TankModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, verbose_name='名前')),
            ],
            options={
                'verbose_name': '水槽',
                'db_table': 'tank',
            },
        ),
        migrations.CreateModel(
            name='WaterQualityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='計測日')),
                ('room_temperature', models.IntegerField(default=0, verbose_name='室温')),
                ('water_temperature', models.IntegerField(default=0, verbose_name='水温')),
                ('pH', models.IntegerField(default=0, verbose_name='ph')),
                ('DO', models.IntegerField(default=0, verbose_name='DO')),
                ('salinity', models.IntegerField(default=0, verbose_name='塩分濃度')),
                ('NH4', models.IntegerField(default=0, verbose_name='NH4')),
                ('NO2', models.IntegerField(default=0, verbose_name='NO2')),
                ('NO3', models.IntegerField(default=0, verbose_name='NO3')),
                ('Ca', models.IntegerField(default=0, verbose_name='Ca')),
                ('Al', models.IntegerField(default=0, verbose_name='Al')),
                ('Mg', models.IntegerField(default=0, verbose_name='Mg')),
                ('notes', models.TextField(blank=True, max_length=512, null=True, verbose_name='備考')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='water_quality', to='rakuraku_apps.tankmodel', verbose_name='水槽')),
            ],
            options={
                'verbose_name': '水質',
                'db_table': 'water_quality',
            },
        ),
    ]
