# Generated by Django 4.1.7 on 2024-08-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rakuraku_apps', '0002_tankmodel_waterqualitymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterqualitymodel',
            name='Al',
            field=models.IntegerField(null=True, verbose_name='Al'),
        ),
        migrations.AlterField(
            model_name='waterqualitymodel',
            name='Ca',
            field=models.IntegerField(null=True, verbose_name='Ca'),
        ),
        migrations.AlterField(
            model_name='waterqualitymodel',
            name='DO',
            field=models.IntegerField(null=True, verbose_name='DO'),
        ),
        migrations.AlterField(
            model_name='waterqualitymodel',
            name='Mg',
            field=models.IntegerField(null=True, verbose_name='Mg'),
        ),
        migrations.AlterField(
            model_name='waterqualitymodel',
            name='NH4',
            field=models.IntegerField(null=True, verbose_name='NH4'),
        ),
        migrations.AlterField(
            model_name='waterqualitymodel',
            name='NO2',
            field=models.IntegerField(null=True, verbose_name='NO2'),
        ),
        migrations.AlterField(
            model_name='waterqualitymodel',
            name='NO3',
            field=models.IntegerField(null=True, verbose_name='NO3'),
        ),
        migrations.AlterField(
            model_name='waterqualitymodel',
            name='pH',
            field=models.IntegerField(null=True, verbose_name='ph'),
        ),
        migrations.AlterField(
            model_name='waterqualitymodel',
            name='room_temperature',
            field=models.IntegerField(verbose_name='室温'),
        ),
        migrations.AlterField(
            model_name='waterqualitymodel',
            name='salinity',
            field=models.IntegerField(null=True, verbose_name='塩分濃度'),
        ),
        migrations.AlterField(
            model_name='waterqualitymodel',
            name='water_temperature',
            field=models.IntegerField(verbose_name='水温'),
        ),
    ]
