# Generated by Django 4.1.7 on 2024-09-04 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rakuraku_apps', '0008_alter_waterqualitymodel_al_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterqualitymodel',
            name='tank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_quality', to='rakuraku_apps.tankmodel', verbose_name='水槽'),
        ),
    ]
